"""criado a model

Revision ID: f7da961dce5a
Revises: 
Create Date: 2021-09-23 18:47:55.991197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7da961dce5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lead_table_email_key', 'lead_table', type_='unique')
    op.drop_constraint('lead_table_phone_key', 'lead_table', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lead_table_phone_key', 'lead_table', ['phone'])
    op.create_unique_constraint('lead_table_email_key', 'lead_table', ['email'])
    # ### end Alembic commands ###
